language: python

matrix:
  include:
    - python: 3.7

install:
 - pip install -U Red-DiscordBot
 - pip install pyparsing
 - pip install timeago
 - pip install ebird-api
 - pip install dataclasses-json

script:
 - pytest
