[tool.poetry]
name = "dronefly"
version = "0.1.0"
description = "Chat platform software for naturalist-related sites"
authors = ["Ben Armstrong <synrg@debian.org>"]
license = "AGPL-3.0-or-later"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8.1,<3.10"
# Old version of Red; please read carefully:
Red-DiscordBot = "^3.4.16"
# 
# This version is required, but doesn't work until https://github.com/python-poetry/poetry/issues/5002 is solved:
#
#   Red-DiscordBot = { git = "https://github.com/Cog-Creators/Red-DiscordBot", branch = "V3/dpy2_unstable" }
# 
# **IMPORTANT!** Red-DiscordBot 3.5.x must therefore be upgraded manually via pip after poetry install:
#
#   $ python -m pip install -U --force-reinstall git+https://github.com/Cog-Creators/Red-DiscordBot@V3/dpy2_unstable#egg=Red-DiscordBot
dataclasses-json = "^0.5.5"
ebird-api = "^3.0.6"
html2markdown = "^0.1.7"
inflect = "^5.3.0"
timeago = "^1.0.15"
aiolimiter = "^1.0.0-beta.1"
aiohttp-retry = "^2.4.5"
pyinaturalist = "^0.15.0"
dateparser = "^1.0.0"

[tool.poetry.group.dev.dependencies]
black = "^21.8-beta.0"
pytest = "^6.2.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
