[tool.bandit]
exclude_dirs = ["tests"]

[tool.flake8]
max-line-length = 100

[tool.poetry]
name = "dronefly"
version = "0.1.1.dev1"
description = "Chat platform software for naturalist-related sites"
authors = ["Ben Armstrong <synrg@debian.org>"]
license = "AGPL-3.0-or-later"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8.1,<3.12"
dronefly-discord = "^0.1.1.dev1"
dronefly-core = "^0.3.6.dev0"
Red-DiscordBot = "^3.5.1"
ebird-api = "^3.0.6"
html2markdown = "^0.1.7"
inflect = "^5.3.0"
timeago = "^1.0.15"
aiolimiter = "^1.0.0"
aiohttp-retry = "^2.4.5"
pyinaturalist = ">=0.19.0.dev2,<0.20"
dateparser = "^1.0.0"

[tool.poetry.group.dev.dependencies]
black = "^22.12.0"
pytest = "^7.2.1"
pytest-mock = "^3.10.0"
pylint = "^2.10.2"
pytest-asyncio = "^0.20.3"

[tool.poetry.group.docs.dependencies]
sphinx = "^5.1.1"
sphinx-rtd-theme = "^1.0.0"
sphinxcontrib_trio = "^1.1.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
