[tool.poetry]
name = "dronefly"
version = "0.1.0"
description = "Chat platform software for naturalist-related sites"
authors = ["Ben Armstrong <synrg@debian.org>"]
license = "AGPL-3.0-or-later"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8.1,<3.10"
dronefly-core = { path = "../dronefly-core", develop = true }
Red-DiscordBot = { git = "https://github.com/Cog-Creators/Red-DiscordBot", rev = "V3/develop"}
dataclasses-json = "^0.5.5"
ebird-api = "^3.0.6"
html2markdown = "^0.1.7"
inflect = "^5.3.0"
timeago = "^1.0.15"
aiolimiter = "^1.0.0"
aiohttp-retry = "^2.4.5"
pyinaturalist = { git = "https://github.com/pyinat/pyinaturalist" }
dateparser = "^1.0.0"

[tool.poetry.group.dev.dependencies]
black = "^22.12.0"
pytest = "^6.2.5"
pytest-mock = "^3.6.1"
pylint = "^2.10.2"
pytest-asyncio = "^0.20.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
