name: Dronefly

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install red-discordbot pyparsing ebird-api dataclasses-json html2markdown inflect aiolimiter
        pip install timeago
    - name: Test with pytest
      run: |
        pip install pytest
        pytest

